/app/miniconda3/bin/accelerate launch --config_file examples/wanvideo/model_training/full/accelerate_config_zero3.yaml examples/wanvideo/model_training/train.py \
  --dataset_base_path data/train_data \
  --dataset_metadata_path data/train_data/metadata.csv \
  --data_file_keys "video,input_audio,s2v_pose_video" \
  --height 576 \
  --width 1024 \
  --num_frames 81 \
  --frame_rate 16 \
  --fix_frame_rate True \
  --dataset_repeat 5 \
  --model_id_with_origin_paths "Wan-AI/Wan2.2-S2V-14B:diffusion_pytorch_model*.safetensors,Wan-AI/Wan2.2-S2V-14B:wav2vec2-large-xlsr-53-english/model.safetensors,Wan-AI/Wan2.2-S2V-14B:models_t5_umt5-xxl-enc-bf16.pth,Wan-AI/Wan2.2-S2V-14B:Wan2.1_VAE.pth" \
  --audio_processor_path "Wan-AI/Wan2.2-S2V-14B:wav2vec2-large-xlsr-53-english/" \
  --learning_rate 1e-5 \
  --num_epochs 100 \
  --trainable_models "dit" \
  --remove_prefix_in_ckpt "pipe.dit." \
  --output_path "./models/train/Wan2.2-S2V-14B_full" \
  --extra_inputs "input_image,input_audio,s2v_pose_video" \
  --use_gradient_checkpointing_offload
